spring.application.name=customer-service
server.port=8081
management.endpoints.web.exposure.include=*
spring.config.import=optional:configserver:http://localhost:8888
#pour choisir quel config env dev,prod, default ...
spring.profiles.active=dev
